web: java -Dserver.port=$PORT -Ddarksky.api.key=$DARKSKY_API_KEY -Dgooglemaps.api.key=$GOOGLEMAPS_API_KEY -Dyellowpages.api.key=$YELLOWPAGES_API_KEY -Dgooglegeocode.api.key=$GOOGLEGEOCODE_API_KEY $JAVA_OPTS -jar app.jar

