web: java -Dserver.port=$PORT -Ddarksky.api.key=$DARKSKY_API_KEY -Dgoogle.maps.api.key=$GOOGLEMAPS_API_KEY -Dyellowpages.api.key=$YELLOW_PAGES_API_KEY -Dgooglegeocode.api.key=GOOGLEGEOCODE_API_KEY $JAVA_OPTS -jar build/libs/backend-0.0.1-SNAPSHOT.jar

